namespace Basilisque.DependencyInjection.Tests.CodeAnalysis
{
    [TestClass]
    public class DependencyInjectionGeneratorTests
    {
        //        [TestMethod]
        //        public async Task MyTestMethod()
        //        {
        //            var code = @"
        ///// <summary>
        ///// Test class for Alex
        ///// </summary>
        ///// <returns></returns>
        //public class AlexTestClass
        //{
        //}
        //";

        //            var generated1 = @"//------------------------------------------------------------------------
        //// <auto-generated>
        ////   This code was generated by a tool.
        ////   Basilisque.DependencyInjection.CodeAnalysis, 1.0.0.0
        ////   
        ////   Changes to this file may cause incorrect behavior and will be lost if
        ////   the code is regenerated.
        //// </auto-generated>
        ////------------------------------------------------------------------------

        //namespace Alex.Test.RNS
        //{
        //    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(""Basilisque.DependencyInjection.CodeAnalysis"", ""1.0.0.0"")]
        //    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        //    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        //    public class DependencyRegistrator
        //    {
        //    }
        //}";

        //            var generated2 = @"//------------------------------------------------------------------------
        //// <auto-generated>
        ////   This code was generated by a tool.
        ////   Basilisque.DependencyInjection.CodeAnalysis, 1.0.0.0
        ////   
        ////   Changes to this file may cause incorrect behavior and will be lost if
        ////   the code is regenerated.
        //// </auto-generated>
        ////------------------------------------------------------------------------

        //namespace TestProject
        //{
        //    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(""Basilisque.DependencyInjection.CodeAnalysis"", ""1.0.0.0"")]
        //    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        //    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        //    public class DependencyRegistrator : Alex.Test.RNS.DependencyRegistrator
        //    {
        //    }
        //}";

        //            await new IncrementalSourceGeneratorVerifier<DependencyInjectionGenerator>
        //            {
        //                GlobalOptions =
        //                {
        //                    { "build_property.RootNamespace", "Alex.Test.RNS" }
        //                },
        //                DiagnosticOptions =
        //                {
        //                    //{ "CS1591", Microsoft.CodeAnalysis.ReportDiagnostic.Suppress }
        //                },
        //                TestState =
        //                {
        //                    //AnalyzerConfigFiles = { },
        //                    Sources = { code },
        //                    GeneratedSources =
        //                    {
        //                        (typeof(DependencyInjectionGenerator), "DependencyRegistrator_RootNamespace.g.cs", SourceText.From(generated1, Encoding.UTF8)),
        //                        (typeof(DependencyInjectionGenerator), "DependencyRegistrator_GlobalNamespace.g.cs", SourceText.From(generated2, Encoding.UTF8)),
        //                    }
        //                }
        //            }.RunAsync();

        //        }
    }
}
